apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code

# Add Grafana on top of base observability stack

resources:
  - ../../otel-collector.yaml
  - ../../servicemonitor.yaml
  - ../../grafana.yaml

patchesStrategicMerge:
  - grafana-datasource-patch.yaml

